spring:
  profile:
    active: dev

---
spring:
  profile: dev
  application:
    name: microservicecloud-config-springcloud-dev

---
spring:
  profile: test
  application:
    name: microservicecloud-config-springcloud-test
